### ISSUE TITLE
Update clean-css to 3.0

### ISSUE THREAD

**Issue by jakubpawlowicz** [brunch/clean-css-brunch#9]
It was released yesterday and here are upgrade instructions: https://github.com/jakubpawlowicz/clean-css#how-to-upgrade-clean-css-from-2x-to-3x

**Comment by jakubpawlowicz** [comment]
Any updates? If not I'll send a PR!

**Comment by es128** [comment]
:+1: a PR would help :smile:

**Comment by jakubpawlowicz** [comment]
I'll make one just bumping the version, source maps are not so straightforward, we can have a separate ticket for it.
